[package]
name = "app_gastos"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf-extract = "0.7.7"
regex = "1.10.4"
slint = "1.6"

[build-dependencies]
slint-build = "1.6"