import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    callback converte-fatura(string, string);
    in property <string> result_msg: "";

    GridLayout {
        padding: 25px;
        spacing: 10px;

        Row {
            Text {
                text: "Conversor de Fatura de PDF";
                font-size: 24px;
                font-weight: 900;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }

        Row {
            GridLayout {
                Row {
                    Text {
                        text: "Arquivo da fatura PDF:";
                        font-size: 16px;
                        font-weight: 400;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }
                Row {
                    pdf_filename := LineEdit {
                        placeholder-text: "Caminho para arquivo PDF";
                        text: "caminho do repo";
                        font-size: 16px;
                        horizontal-alignment: center;
                    }
                }
            }
        }

        Row {
            GridLayout {
                Row {
                    Text {
                        text: "Nome do arquivo de saida (CSV):";
                        font-size: 16px;
                        font-weight: 400;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }
                Row {
                    csv_filename := LineEdit {
                        placeholder-text: "Nome do arquivo CSV";
                        font-size: 16px;
                        horizontal-alignment: center;
                    }
                }
            }
        }
        
        Row {
            Button {
                text: "Converter";
                height: 35px;
                clicked => {converte-fatura(pdf-filename.text, csv-filename.text)}
            }
        }

        Row {
            Text {
                text: root.result_msg;
                font-size: 16px;
                font-weight: 400;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }
    }
}
