import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    callback converte-fatura(string, string);
    in property <string> result_msg: "";
    in property <string> execution_path: "";

    GridLayout {
        padding: 25px;
        spacing: 10px;

        Row {
            Text {
                text: "PDF Invoice Converter";
                font-size: 24px;
                font-weight: 900;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }

        Row {
            GridLayout {
                Row {
                    Text {
                        text: "PDF Invoice file:";
                        font-size: 16px;
                        font-weight: 400;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }
                Row {
                    pdf_filename := LineEdit {
                        placeholder-text: "PDF invoice file path";
                        text: root.execution_path;
                        font-size: 16px;
                        horizontal-alignment: center;
                    }
                }
            }
        }

        Row {
            GridLayout {
                Row {
                    Text {
                        text: "Output file name (CSV):";
                        font-size: 16px;
                        font-weight: 400;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }
                Row {
                    csv_filename := LineEdit {
                        placeholder-text: "CSV file name";
                        font-size: 16px;
                        horizontal-alignment: center;
                    }
                }
            }
        }
        
        Row {
            Button {
                text: "Convert";
                height: 35px;
                clicked => {converte-fatura(pdf-filename.text, csv-filename.text)}
            }
        }

        Row {
            Text {
                text: root.result_msg;
                font-size: 16px;
                font-weight: 400;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }
    }
}
